---
- name: Disable SELinux
  selinux:
    state: "{{ selinux_state }}"

- name: Disable IPTables
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - firewalld

- name: Install common packages
  package:
    name:   "{{ item }}"
    state:  present
  with_items:
    - git
    - net-tools
    - unzip
    - wget


